# ビルド日時(JST)からバージョン情報ヘッダ(sakura_core/config/build_version_generated.h)を
# 自動生成する。preBuild.bat から毎ビルド呼び出される。
#
# 同じ日(JST)に複数回ビルドすると PR_LV_SUFFIX に a, b, c... と枝番が付く。
#   1回目: PR_LV=260815 PR_LV_SUFFIX=""   → 2.3.2.260815
#   2回目: PR_LV=260815 PR_LV_SUFFIX="a"  → 2.3.2.260815a
#   3回目: PR_LV=260815 PR_LV_SUFFIX="b"  → 2.3.2.260815b
$ErrorActionPreference = "Stop"

$outDir     = Join-Path $PSScriptRoot "..\sakura_core\config"
$headerPath = Join-Path $outDir "build_version_generated.h"
$statePath  = Join-Path $outDir ".build_version_state"

$jst   = [System.TimeZoneInfo]::FindSystemTimeZoneById("Tokyo Standard Time")
$today = [System.TimeZoneInfo]::ConvertTime([DateTime]::UtcNow, $jst).ToString("yyMMdd")

$count = 0
if (Test-Path $statePath) {
    $lines = Get-Content $statePath
    if ($lines.Count -ge 2 -and $lines[0] -eq $today) {
        $count = [int]$lines[1] + 1
    }
}
Set-Content -Path $statePath -Value @($today, $count) -Encoding ascii

# 0→"" 1→"a" 2→"b" ... 26→"z" 27→"aa" ... (bijective base-26)
function Get-Suffix([int]$n) {
    if ($n -le 0) { return "" }
    $n -= 1
    $suffix = ""
    while ($true) {
        $suffix = [string][char]([int][char]'a' + ($n % 26)) + $suffix
        $n = [int]($n / 26) - 1
        if ($n -lt 0) { break }
    }
    return $suffix
}

$suffix = Get-Suffix $count

New-Item -ItemType Directory -Force -Path $outDir | Out-Null

$header = @"
// Auto-generated by gen_build_version.ps1 on every build. Do not edit manually.
#ifndef BUILD_VERSION_GENERATED_H
#define BUILD_VERSION_GENERATED_H
#define PR_LV        $today
#define PR_LV_STR    "$today"
#define PR_LV_SUFFIX "$suffix"
#endif // BUILD_VERSION_GENERATED_H
"@

Set-Content -Path $headerPath -Value $header -Encoding ascii
