# ビルド日時(JST)からバージョン情報ヘッダ(sakura_core/config/build_version_generated.h)を
# 自動生成する。preBuild.bat から毎ビルド呼び出される。
#
# バージョン表記は "2.3.yy.mddx" 形式(yy=西暦下2桁、mdd=月[ゼロ埋めなし]+日[2桁ゼロ埋め]
# で3〜4桁、x=同日ビルドの枝番)。同じ日(JST)に複数回ビルドすると x(PR_LV_SUFFIX)に
# a, b, c... と枝番が付く。
#   1回目: PR_LV_YY=26 PR_LV_MDD=815  PR_LV_SUFFIX=""   → 2.3.26.815   (8月15日)
#   2回目: PR_LV_YY=26 PR_LV_MDD=815  PR_LV_SUFFIX="a"  → 2.3.26.815a
#   3回目: PR_LV_YY=26 PR_LV_MDD=815  PR_LV_SUFFIX="b"  → 2.3.26.815b
$ErrorActionPreference = "Stop"

$outDir     = Join-Path $PSScriptRoot "..\sakura_core\config"
$headerPath = Join-Path $outDir "build_version_generated.h"
$statePath  = Join-Path $outDir ".build_version_state"

$jst = [System.TimeZoneInfo]::FindSystemTimeZoneById("Tokyo Standard Time")
$now = [System.TimeZoneInfo]::ConvertTime([DateTime]::UtcNow, $jst)

# 同日判定用のキー(枝番リセットの境界)。表示形式そのものではなく、日が変わったかだけを
# 一意に判定できればよいので、従来通りyyMMddの6桁をそのまま使う。
$today  = $now.ToString("yyMMdd")
$yyStr  = $now.ToString("yy")    # 西暦下2桁、常に2桁ゼロ埋め(例: "26")
$mddStr = $now.ToString("Mdd")   # 月(ゼロ埋めなし)+日(2桁ゼロ埋め)、3〜4桁(例: 8/15→"815", 11/5→"1105")
$yyNum  = [int]$yyStr
$mddNum = [int]$mddStr

$count = 0
if (Test-Path $statePath) {
    $lines = Get-Content $statePath
    if ($lines.Count -ge 2 -and $lines[0] -eq $today) {
        $count = [int]$lines[1] + 1
    }
}
Set-Content -Path $statePath -Value @($today, $count) -Encoding ascii

# 0→"" 1→"a" 2→"b" ... 26→"z" 27→"aa" ... (bijective base-26)
function Get-Suffix([int]$n) {
    if ($n -le 0) { return "" }
    $n -= 1
    $suffix = ""
    while ($true) {
        $suffix = [string][char]([int][char]'a' + ($n % 26)) + $suffix
        $n = [int]($n / 26) - 1
        if ($n -lt 0) { break }
    }
    return $suffix
}

$suffix = Get-Suffix $count

New-Item -ItemType Directory -Force -Path $outDir | Out-Null

$header = @"
// Auto-generated by gen_build_version.ps1 on every build. Do not edit manually.
#ifndef BUILD_VERSION_GENERATED_H
#define BUILD_VERSION_GENERATED_H
#define PR_LV_YY      $yyNum
#define PR_LV_YY_STR  "$yyStr"
#define PR_LV_MDD     $mddNum
#define PR_LV_MDD_STR "$mddStr"
#define PR_LV_SUFFIX  "$suffix"
#endif // BUILD_VERSION_GENERATED_H
"@

Set-Content -Path $headerPath -Value $header -Encoding ascii
